CREATE TABLE USUARIOS (
    USUARIO_ID CHAR(10) PRIMARY KEY NOT NULL,
    USUARIO_NOMBRE VARCHAR(50) NOT NULL,
    USUARIO_APELLIDO VARCHAR(50) NOT NULL,
    USUARIO_CORREO VARCHAR(100) NOT NULL,
    USUARIO_PWD VARCHAR(255) NOT NULL,
    USUARIO_ROL ENUM('ADMINISTRADOR', 'CLIENTE', 'EMPLEADO') NOT NULL DEFAULT 'CLIENTE',
    UNIQUE(USUARIO_CORREO)
);

--TABLA UNICAMENTE DE INFORMACION DE LOS CHEFS
-- NO SE UTILIZA EN EL PROCESO DE REGISTRO DE CHEFS
CREATE TABLE CHEF {
    CHEF_NOMBRE VARCHAR(50) NOT NULL,
    CHEF_DESCRIPCION VARCHAR(255) NOT NULL,
    CHEF_IMAGEN VARCHAR(255) NOT NULL,
}